lane :test do
  webhook_url = "https://outlook.office.com/webhook/..."
  teamify(
    summary: "Test summary",
    title: "Test title",
    sub_title: "Test subtitle",
    image: "",
    facts:[
      {
        "name"=>"Platform",
        "value"=>"Android"
      }
    ],
    teams_webhook_url: webhook_url
  )
end